### ISSUE TITLE
LSB for centaur in instruments.py

### ISSUE THREAD

**Issue by vialb** [eost/clb-noise-analysis#10]
C'est Coralie Aubert qui nous a fait remarqué que le paramètre LSB dans instruments.py pour la centaur est erroné : 
**centaur = {'lsb': 2.5000075000225e-07}**

La centaur configurée en 40Vpp donne 40/2^24 = 2,38 10^-6 et nano le met à env. 2,5 10^-6
du coup il faut mettre :
**centaur = {'lsb': 2.5000075000225e-06}**

Je trouvais étrange aussi que ma station de prospection installée au sol avait un niveau de bruit aussi faible ...

**Comment by bonaime** [comment]
Corrigé dans la dernière version
d73ae6a6da68fad935b098e9a6ab872f2d928ba3
Merci
